namespace HachijouBot.ElectronicObserverReport;

public enum UseItemId
{
	Unknown = 0,
	InstantRepair = 1,
	InstantConstruction = 2,
	DevelopmentMaterial = 3,
	ImproveMaterial = 4,
	FurnitureBoxSmall = 10,
	FurnitureBoxMedium = 11,
	FurnitureBoxLarge = 12,

	/// <summary>
	/// Generic ID for different items? The actual item ID is api_item.api_id
	/// </summary>
	Item = 13,
	Senka = 18,
	Fuel = 31,
	Ammo = 32,
	Steel = 33,
	Bauxite = 34,
	FurnitureCoin = 44,
	DockKey = 49,
	RepairTeam = 50,
	RepairGoddess = 51,
	FurnitureFairy = 52,
	PortExpensionSet = 53,
	MoraleFoodMamiya = 54,
	MarriageRingAndPapers = 55,
	ValentineChocolate = 56,
	Medals = 57,
	RemodelBlueprints = 58,
	MoraleFoodIrako = 59,
	PresentBox = 60,
	FirstClassMedal = 61,
	Hishimochi = 62,
	HeadquartersPersonnel = 63,
	ReinforcementExpansion = 64,
	PrototypeFlightDeckCatapult = 65,
	CombatRation = 66,
	UnderwayReplenishment = 67,
	Saury = 68,
	CannedSaury = 69,
	SkilledCrewMember = 70,
	NeTypeEngine = 71,
	DecorationMaterial = 72,
	ConstructionBattalion = 73,
	NewModelAircraftBlueprint = 74,
	NewModelArtilleryArmamentMaterials = 75,
	CombatRationSpecialOnigiri = 76,
	NewModelAviationArmamentMaterials = 77,
	ActionReport = 78,
	StraitMedal = 79,
	XmasSelectGiftBox = 80,
	ShoGoMedalKou = 81,
	ShoGoMedalOtsu = 82,
	ShoGoMedalHei = 83,
	ShoGoMedalTei = 84,
	Rice = 85,
	Umeboshi = 86,
	Nori = 87,
	Tea = 88,
	HoushouDinnerTicket = 89,
	SetsubunBeans = 90,
	EmergencyRepairMaterial = 91,
	NewModelRocketDevelopmentMaterials = 92,
	Sardine = 93,
	NewModelArmamentMaterials = 94,
	SubmarineSupplyMaterials = 95,
	Pumpkin = 96,
	TeruTeruBozu = 97,
	SeaColoredRibbon = 98,
	WhiteSash = 99,
	LatestOverseasWarshipTechnology = 100,
}
